# ./.github/actions/python-lint/action.yml

name: "Python Lint"
description: "Runs a linter on Python code"

inputs:
  python-version:
    description: "Version of Python to use"
    required: true
    default: "3.8"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run Linter
      run: |
        flake8 .
      shell: bash
