name: "Python Lint"
description: "Runs a linter on Python code"
inputs:
  python-version:
    description: "Version of Python to use"
    required: true
    default: "3.8"
runs:
  using: "bash"
  steps:
    - name: Install Dependencies
      run: |
        pip install flake8
    - name: Run Linter
      run: |
        flake8 .
