# ./.github/actions/python-test/action.yml

name: "Python Test"
description: "Runs tests using pytest"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: |
        pytest

inputs:
  python-version:
    description: "Version of Python to use"
    required: true
    default: "3.8"
