name: "Python Test"
description: "Runs tests using pytest"

inputs:
  python-version:
    description: "Version of Python to use"
    required: true
    default: "3.8"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      run: |
        echo "Setting up Python version ${{ inputs.python-version }}"
      shell: bash

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
      shell: bash

    - name: Run Tests
      run: |
        pytest
      shell: bash
