# ./.github/workflows/deploy.yml

name: Deploy

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - release/*
      - '*' # Run on any other branch
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Activate virtual environment (Windows)
        run: |
          if [ ! -d ".venv" ]; then
            python -m venv .venv
          fi
          source .venv/Scripts/activate
        shell: bash

      - name: Install Dependencies
        run: |
          source .venv/Scripts/activate
          pip install -r requirements.txt
          pip install pytest
        shell: bash

      - name: Deploy
        run: |
          # Add your deployment commands here
          echo "Deploying to production..."
        shell: bash


