# ./.github/workflows/deploy.yml

name: Deploy

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - release/*
      - '*' # Run on any other branch
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
        shell: bash

      - name: Deploy
        run: |
          # Add your deployment commands here
          echo "Deploying to production..."
        shell: bash


